define({
    //#region Rota infrastructure resources
    rota: {
        bimar: "Bimar Information Technology 2015",
        username: 'User Name',
        password: 'Password',
        invalid_grant: 'Failed to login,please check your credentials',
        kategoriler: 'Categories',
        cachetemizle: 'Clear Cache',
        dildegistir: 'Switch Language',
        tamam: 'OK',
        onay: 'Confirm',
        iptal: 'Cancel',
        yenile: 'Refresh',
        arama: 'Search...',
        paylasimdahata: 'Error in sharing...{0}',
        lutfenbekleyiniz: 'Please Wait..',
        dilsecimiyapiniz: 'Please choose language',
        dildegisimonay: 'Are you sure to change the current language ?',
        dildegisimtamamlandi: 'Current language has been set to {0}',
        zatensecilidilaktif: 'Current language already set to {0}',
        ayarlar: 'Settings',
        cachesilmeonay: "Are you sure to clear the cache ?",
        cachetemizlendi: 'Cache is clear now !',
        login: 'Login',
        giris: 'Log in',
        degergirin: 'Fill in input...',
        detay: 'Detail',
        kopyala: 'Copy to clipboard',
        paylas: 'Share',
        whatsapppaylas: 'Share via WhatsApp',
        kopyalandi: 'Copied',
        basariylapaylastiniz: 'Shared',
        yukleniyor: 'Please wait...',
        kullanicipasswordgiriniz: 'Provide username and password !',
        iletisim: 'Contact us',
        cikis: 'Sign out',
        kapat: 'Quit',
        cikisonay: 'Are you sure to log off ?',
        geri: 'Back',
        offline: 'Network connection failed !',
        hata: 'Error',
        yenidenbaslat: 'Restart !',
        hataolustu: 'An error occured !',
        hataozur: 'Apologize for inconvenience situation.We have been informed about the exception.We will fix it soon.',
        hataaciklama: 'Error description :',
        mailfromzorunlu: 'From field is missing',
        mailtozorunlu: 'TO field is missing',
        mailgonderimindehata: 'Mail sending is failed',
        mailbodyzorunlu: 'Body is missing !',
        introyugec: 'Skip Intro',
        sonraki: 'Previous',
        onceki: 'Next',
        kullanmayabasla: 'Start using app',
        intro: 'Intro',
        uygdurduruldu: 'App is disabled temporarly due to some specific reason.You will be notified about this issue as soon as posible',
        verhatali: 'New version found (ver : {0}).Please always use the latest version'
    },
    //#endregion

    //#region Ynl resources
    ynl: {
        uygulama: 'YNL Safe Mobile',
        kasahareketliste: 'Safe Movements',
        reddet: 'Reject',
        reddetonay: 'Are you sure to reject?',
        onayla: 'Approve',
        filtre: 'Filter',
        temizle: 'Clear',
        filtrele: 'Filter',
        bastarihi: 'Start Date',
        bittarihi: 'End Date',
        onaydurumu: 'Approve Status',
        bekliyor: 'Pending',
        onaylandi: 'Approved',
        reddedildi: 'Rejected',
        hizmet: 'Service',
        hareketbilgileri: 'Movement Info',
        tarih: 'Date',
        tutar: 'Amount',
        aciklama: 'Description',
        hareketdetay: 'Movement Details',
        onaylistesi: 'Approval List',
        kullanici: 'User',
        durum: 'Status',
        onaybasarilimesaji: 'Safe movement approved !',
        reddetbasarilimesaji: 'Safe movement rejected !',
        tumunuonayla: 'Approve all',
        tumunureddet: 'Reject all',
        tumonaybasarilimesaji: 'All movements approved !',
        tumreddetbasarilimesaji: 'All movements rejected !',
        listebaslik: 'Movements on your approval',
        tumuonayonaymesaji: 'All movements will be approved ?',
        tumureddetonaymesaji: 'All movements will be rejected ?',
        toplamlar: 'Safe Summary',
        devir: 'Transfer',
        toplamgelir: 'Income Total',
        toplamcikis: 'Exp Total',
        bakiye: 'Remaining',
        bakiyeuah: 'Remaining (UAH)',
        bakiyeusd: 'Remaining (USD)',
        hareketbulunamadi: 'No movement found.You are attempting to display previously approved/rejected item',
        gonder: 'Send',
        adi: 'Your Name',
        konu: 'Subject',
        mesaj: 'Message',
        iletisim: 'Contact Form',
        email: 'E-mail',
        hakkinda: 'YNL Safe Mobile Application developed by Bimar Information Technology',
        hakkinda2: ' Tel : +90 232 765 90 66 Fax : +90 232 765 90 77  Email:_ArkasLojistikYazilimMailGrubu@arkas.com',
        emailbasarilimesaji: 'Your message is successfully sent ',
        hakkimizda: 'About Us',
        intro: 'Welcome to YNL Safe Application'
    }
    //#endregion
});