define({
    //#region Rota infrastructure resources
    rota: {
        bimar: "Bimar Bilgi İşlem Hizmetleri 2015",
        username: 'Kullanıcı Adı',
        password: 'Şifre',
        invalid_grant: 'Login başarısız,lütfen bilgilerinizi kontrol ediniz.',
        kategoriler: 'Kategoriler',
        cacheTemizle: 'Cache Temizle',
        dildegistir: 'Dil Değiştir',
        tamam: 'Tamam',
        iptal: 'İptal',
        onay: 'Onay',
        yenile: 'Yenile',
        arama: 'Ara...',
        paylasimdahata: 'Paylaşımda hata oluştu...{0}',
        lutfenbekleyiniz: 'Lütfen Bekleyiniz...',
        dilsecimiyapiniz: 'Dil seçimi yapınız',
        dildegisimonay: 'Aktif dili değiştirmek istiyormusunuz ?',
        dildegisimtamamlandi: 'Dil {0} olarak değiştirildi',
        zatensecilidilaktif: 'Aktif dil zaten {0}',
        ayarlar: 'Ayarlar',
        cachesilmeonay: "Cache'i temizlemek istediğinize eminmisiniz ?",
        cachetemizlendi: 'Cache temizlendi !',
        login: 'Kullanıcı Girişi',
        giris: 'Giriş',
        degergirin: 'Değer giriniz...',
        detay: 'Detay',
        kopyala: 'Kopyala',
        paylas: 'Paylaş',
        whatsapppaylas: 'WhatsApp"da paylaş',
        kopyalandi: 'Kopyalandı',
        basariylapaylastiniz: 'Paylaşıldı',
        yukleniyor: 'Lütfen bekleyiniz...',
        kullanicipasswordgiriniz: 'Kullanıcı adı ve şifreyi kontrol ediniz !',
        iletisim: 'İletişim',
        cikis: 'Çıkış',
        kapat: 'Uygulamayi kapat',
        cikisonay: 'Aktif kullanıcıdan çıkış yapılacak ?',
        geri: 'Geri',
        offline: 'Internet bağlantınız kesildi !',
        hata: 'Hata',
        yenidenbaslat: 'Yeniden başlat !',
        hataolustu: 'Uygulamada hata oluştu !',
        hataozur: 'Oluşan hata yüzünden özür dileriz,hata ile ilgili bilgiler sistemimize kayit edildi.En yakın zamanda sorunu çözeceğiz.',
        hataaciklama: 'Hata detayi :',
        mailfromzorunlu: 'From alanı boş olamaz',
        mailtozorunlu: 'TO alanı boş olamaz',
        mailgonderimindehata: 'Mail gönderilemedi !',
        mailbodyzorunlu: 'Mail içeriği boş olamaz !',
        introyugec: 'Sunumu geç',
        sonraki: 'Sonraki',
        onceki: 'Önceki',
        kullanmayabasla: 'Kullanmaya başla',
        intro: 'Intro',
        uygdurduruldu: 'Uygulama geçici süreliğine kullanım dışıdır.Konu hakkında en kısa sürede bilgilendiriliceksiniz.',
        verhatali:'Yeni versiyon bulundu (ver : {0}).Lütfen her zaman güncel versiyonu kullanınız'

    },
    //#endregion

    //#region Ynl resources
    ynl: {
        uygulama: 'YNL Kasa Mobil',
        kasahareketliste: 'Kasa Hareketleri',
        reddet: 'Reddet',
        reddetonay: 'Reddetmek istediğinize emin misiniz?',
        onayla: 'Onayla',
        filtre: 'Filtre',
        temizle: 'Temizle',
        filtrele: 'Filtrele',
        bastarihi: 'Baş. Tarihi',
        bittarihi: 'Bit. Tarihi',
        onaydurumu: 'Onay Durumu',
        bekliyor: 'Bekliyor',
        onaylandi: 'Onaylandı',
        reddedildi: 'Reddedildi',
        hizmet: 'Hizmet',
        hareketbilgileri: 'Hareket Bilgileri',
        tarih: 'Tarih',
        tutar: 'Tutar',
        aciklama: 'Açıklama',
        hareketdetay: 'Hareket Detayları',
        onaylistesi: 'Onay Listesi',
        kullanici: 'Kullanıcı',
        durum: 'Durum',
        onaybasarilimesaji: 'Hareket onaylandi !',
        reddetbasarilimesaji: 'Hareket reddedildi !',
        tumunuonayla: 'Tümünü Onayla',
        tumunureddet: 'Tümünü Reddet',
        tumonaybasarilimesaji: 'Tüm hareketler onaylandı !',
        tumreddetbasarilimesaji: 'Tüm hareketler reddedildi !',
        listebaslik: 'Onayınızı bekleyen kayıtlar',
        tumuonayonaymesaji: 'Tüm hareketler onaylanacak ?',
        tumureddetonaymesaji: 'Tüm hareketler reddedilecek ?',
        toplamlar: 'Toplamlar',
        devir: 'Devir',
        toplamgelir: 'Toplam Gelir',
        toplamcikis: 'Toplam Çıkış',
        bakiye: 'Bakiye',
        bakiyeuah: 'Bakiye (UAH)',
        bakiyeusd: 'Bakiye (USD)',
        hareketbulunamadi: 'Hareket bulunamadı.Önceden onaylanmış bir kayda ulaşmaya çalışıyorsunuz',
        adi: 'Ad Soyad',
        email: 'E-posta',
        konu: 'Konu',
        iletisim: 'İletisim Formu',
        mesaj: 'Mesaj',
        gonder: 'Gönder',
        hakkinda: 'YNL Kasa Mobil Uygulaması Bimar Bilgi İşlem Hizmetleri tarafından geliştirilmiştir.',
        hakkinda2: ' Tel : +90 232 765 90 66 Fax : +90 232 765 90 77  Email:_ArkasLojistikYazilimMailGrubu@arkas.com',
        emailbasarilimesaji: 'Mesajınız başarıyla gönderilmiştir',
        hakkimizda: 'Hakkımızda',
        intro: 'YNL Kasa Mobile uygulamasına hoşgeldiniz',
    }
    //#endregion
});